---
booktitle: Proceedings of the 31st  Conference On Learning Theory
shortname: COLT
volume: 75
year: '2018'
start: 2018-07-06
end: 2018-07-09
published: 2018-07-03
location: Stockholm, Sweden
sections:
- name: Preface
  title: Preface
- name: Best Paper Awards
  title: Best Paper Awards
- name: Regular Papers
  title: Regular Papers
- name: Open Problems
  title: Open Problems
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: COLT-2018
month: 0
cycles: false
bibtex_editor: Bubeck, S\'ebastien and Perchet, Vianney and Rigollet, Philippe
editor:
- given: Sébastien
  family: Bubeck
- given: Vianney
  family: Perchet
- given: Philippe
  family: Rigollet
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 31st  Conference On Learning Theory on 06-09 July 2018

  Published as Volume 75 by the Proceedings of Machine Learning Research on 03 July 2018.

  Volume Edited by:
    Sébastien Bubeck
    Vianney Perchet
    Philippe Rigollet

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 06--09 Jul
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v75"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v75
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Conference On Learning Theory
  url: http://www.learningtheory.org/colt2018/index.html
  location: ''
  dates:
  - 2018-07-06
  - 2018-07-07
  - 2018-07-08
  - 2018-07-09
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
